name: Deploy EKS cluster
on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        required: false
        description: use if you want to create a cluster
        options:
          - create
          - delete
      cluster_name:
        required: false
        description: cluster to delete
            
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    ENVIRONMENT_STAGE: dev

jobs:
  deploy_cluster:
    runs-on: ubuntu-latest
    steps:
      - name: install aws cli
        run: |
           aws --version

      - name: install kubectl
        run: |
            curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.7/2023-11-14/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
            kubectl version --client
            echo $PATH
      - name: install eksctl
        run: |
           curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C .
           chmod +x ./eksctl
           cp ./eksctl $HOME/bin/eksctl && export PATH=$HOME/bin:$PATH          
           ls -l $HOME/bin/eksctl
           eksctl version

      - uses: actions/checkout@v3
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::068456885903:role/github-actions-test-role
            aws-region: us-east-1
            role-skip-session-tagging: true
      
      - name: create EKS cluster
        if: ${{ inputs.action == 'create' }}
        working-directory: eksctl
        run: |
          echo "Deployment started on $(date)"
          echo Deploying EKS cluster: stage $ENVIRONMENT_STAGE
          export PATH=$HOME/bin:$PATH 
          echo creating cluster...

        #   eksctl create cluster --configure-file=create-initial-cluster.yml
       

      - name: delete EKS cluster
        if: ${{ inputs.action == 'delete' }}
        working-directory: eksctl
        env:
            CLUSTER_NAME: ${{ inputs.cluster_name }}
        run: |
          echo "Deployment started on $(date)"
          echo Deploying EKS cluster: stage $ENVIRONMENT_STAGE
          export PATH=$HOME/bin:$PATH 
          echo deleting cluster...

        #   eksctl delete cluster --region eu-west-1 --name $CLUSTER_NAME
          
      - name: Post build step
        run: echo "Deployment completed on $(date)"