name: Deploy EKS cluster
on:
  workflow_dispatch:

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    ENVIRONMENT_STAGE: dev

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: install aws cli
        run: |
           aws --version

      - name: install kubectl
        run: |
            curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.7/2023-11-14/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
            kubectl version --client
      - name: install eksctl
        run: |
           curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
           mv /tmp/eksctl $HOME/bin
           eksctl version

      - uses: actions/checkout@v3
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::068456885903:role/github-actions-test-role
            aws-region: us-east-1
            role-skip-session-tagging: true
      

      - name: deploy to AWS
        run: |
          echo "Deployment started on $(date)"
          echo Deploying EKS cluster: stage $ENVIRONMENT_STAGE
          
      - name: Post build step
        run: echo "Deployment completed on $(date)"